# Generated by Django 2.2.5 on 2020-12-17 11:54

from django.db import migrations, models
import queuemining.validator


class Migration(migrations.Migration):

    dependencies = [
        ('queuemining', '0002_auto_20201127_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/', validators=[queuemining.validator.validate_file_extension])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.IntegerField(default=1)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='data',
            name='timestep',
            field=models.ManyToManyField(to='queuemining.TimeStep'),
        ),
    ]
